name: Publishing notes
on:
  workflow_dispatch: null
  push:
    branches:
      - main
    paths:
      - notes/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Logseq Publish
        uses: logseq/publish-spa@v0.3.0
        with:
          graph-directory: notes
          output-directory: _site
      - name: Add a nojekyll file
        run: touch $GITHUB_WORKSPACE/_site/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
